name: Pull Request

on:
  pull_request:
    branches: [master, release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    env:
      CI: 1
      HUSKY: 0 # disables husky hooks
      NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions: 
      statuses: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --no-progress --ignore-scripts

      - name: Verify
        run: make verify
        env:
          SKIP_INSTALL: 1 # install with cache was done already

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: 'coverage/clover.xml'
          threshold_alert: 80
          threshold_warning: 90
